### ISSUE TITLE
Separate the Import and Render Parts of the Tool

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#11]
The `domain` YAML file works well as a database and central area for the storage of data imported from the zip file. The templates could then use this data to render.

- Import/Parse - To load the data into a node YAML file that can be used
- Render - To take the data from the YAML files and render a template

**Comment by DavidMarchant** [comment]
Note: the increased complexity to the command structure that this change brings will merit the use of a CLI library - namely [commander](https://github.com/commander-rb/commander) to be inline & compatible with other Alces projects
