### ISSUE TITLE
Drop Group Arguments and read groups from zips

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#14]
The data gatherer script will handle providing primary and secondary groups (#13) so the CLI no longer needs to worry about them

**Comment by DavidMarchant** [comment]
Additional to the task of dropping the option for groups from the CLI is the task of implementing reading a nodes groups from it's zip. With the merging of https://github.com/alces-software/inventoryware/pull/19 the functionality for specifying a nodes groups on zip creation is present in the gatherer script. 

As such it's now necessary to read a nodes' groups from the `groups` file in the zip if it is present.
