### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#40]
Ensure that there's a license file in the top level and that all the scripts have the appropriate licensing information in them.

(@mjtko we may need your input here)

**Comment by mjtko** [comment]
Re: having boilerplate in all scripts: I think @WilliamMcCumstie may have some magic that does this, seem to remember he added something similar to Cloudware.

Re: which license, dual-license AGPLv3/other-at-our-discretion is our usual approach, e.g. https://github.com/alces-software/flight-direct/blob/develop/LICENSE.txt
