### ISSUE TITLE
Ability to Edit Parsed Data

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#51]
Currently the `modify` command allows editing of the `mutable` data heading. Going forward it would be ideal to have some sort of interactive editing that doesn't rely on CLI options. 

The edit tool therefore could open a text editor on the data or perhaps have some controls in place to prevent certain areas of the data from being overridden. There is need for further discussion as to how we'd like to use and implement this.

**Comment by DavidMarchant** [comment]
The storage of rendered data has been removed and as such it will only be necessary to edit parsed (.yaml) data
