### ISSUE TITLE
Reconsider Directory Structure

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#54]
**This issue is pretty low priority compared to the rest of the Sandbox project so don't worry too much about getting this in right away**

Currently both ruby helper functions and the example template are stored in the `plugins` directory. It may be more logical to consider using `plugins` just for the helpers (or maybe `helpers`/`utils`) and `templates` for the example template (which could then also house the BIOS template info [#52])

**Comment by DavidMarchant** [comment]
It's also worth noting on the topic of directory structure that #55 will necessitate splitting of `store/` to contain both nodes' data & rendered output
