### ISSUE TITLE
Rendering Helpers

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#57]
## Enhancment
With the idea of adding support for rendering templates from within templates I believe it's worth having a helper method in order to minimise the Ruby madness happening in the templates.

The subrender helper will need to:
- Pass the current node object through
- Ensure that the buffer values of the parent template aren't overwritten

## Examples

A snippet of a test template with a subrender command
```
<%= node_data['name'] %>:
  name: <%= node_data['name'] %>
  primary_group: <%= node_data['mutable']['primary_group'] %>
  secondary_group: <%= node_data['mutable']['secondary_groups'] %>
  info: |
    # System

    ## BIOS Version

    <%= find_hashes_with_key_value(node_data, 'id', 'firmware')&.first['version'] %>
    <%= Erubis::Eruby.new(File.read('/opt/inventoryware/plugins/bios_template.md.erb'), bufvar: 'stuoverride').result(binding) %>

    ## System Serial Number

    <%= node_data['lshw']['list']['node']['serial'] %>
```

The template it subrenders
```
    hello <%= node_data['name'] %>
    some
    here
```

The `bufvar: 'stuoverride'` is really important, otherwise the render will overwrite the parent render data.

Currently, that Erubis command is pretty heavy and involved so something which can handle renaming the bufvar on the fly and just simply take a file to render as an argument

**Comment by mjtko** [comment]
Just to add that `bufvar: 'stuoverride'` may not be necessary if this code is pulled into a helper as it may be context/scope bound (i.e. only needed when directly rendering ERB using the same `binding`), so I'd try without it first to see if it works.

Otherwise a `bufvar: "inventoryware#{monotonically_incremented_counter}"` approach might be required.
