### ISSUE TITLE
Output multiple node outputs to same file

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#9]
Rendered templates currently output to a file named after the node and the template but in our use case we'd want to create a single output file from all the renders of the template. 

Can we add the ability to specify the output file to create/append rendered templates to?

**Comment by DavidMarchant** [comment]
Will this output location exclusively be relative to `/opt/inventoryware/output/` or should it be valid for anywhere in the system?

**Comment by ColonelPanicks** [comment]
Let it be anywhere on the system

**Comment by DavidMarchant** [comment]
We have decided to no longer append templates - but have implemented the ability to specify output location in  #10. As a result, this issue will be closed.
