### ISSUE TITLE
BIOS templates contain indentation to work with a specific render template

### ISSUE THREAD

**Issue by ste78** [alces-software/inventoryware#90]
Additional templates currently contain the indentation for them to work with the render template - we need to either work out a way for the partial templates to have the indentation added when they are included, or rethink how we've implemented this as at the moment theres little point having them in separate files because the one relies on formatting set in the other.

**Comment by ColonelPanicks** [comment]
The BIOS templates do not actually have starting indentation. In the example_template the proper indentation is sorted through a fairly hacky split/join:

https://github.com/alces-software/inventoryware/blob/0e2500366182f89dc9cf2d9469d5577f4b3da073/templates/example_template.md.erb#L72

So BIOS templates can be rendered separately without having weird indentation.
