### ISSUE TITLE
Map truncates number of lines if empty, Ideally we want to set maximum number of ports

### ISSUE THREAD

**Issue by ste78** [alces-software/inventoryware#92]
When creating a new map for an asset I want to set the number of ports, I can press enter 48 times and create 48 ports but if I leave lines blank it only stores the last number that has a value set

**Comment by DavidMarchant** [comment]
@atoghill this will just involve removing the `unless line.empty?` from https://github.com/alces-software/inventoryware/blob/97de42ae0c69587f90bb9f394de6bf0fb14210c2/lib/inventoryware/commands/modifys/map.rb#L62

**Comment by atoghill** [comment]
> 
> 
> @atoghill this will just involve removing the `unless line.empty?` from
> 
> [inventoryware/lib/inventoryware/commands/modifys/map.rb](https://github.com/alces-software/inventoryware/blob/97de42ae0c69587f90bb9f394de6bf0fb14210c2/lib/inventoryware/commands/modifys/map.rb#L62)
> 
> Line 62 in [97de42a](/alces-software/inventoryware/commit/97de42ae0c69587f90bb9f394de6bf0fb14210c2)
>  map[i+1] = line unless line.empty? 
> 
> Not wholly sure why i added that :)

It is slightly more complicated than that. When splitting the string provided it does not keep the trailing line breaks. So any empty lines after the last line with a value are not even iterated over. If you want to keep those trailing line breaks you can use `lines` to go over every line in the string and then cleanup the new line characters afterwards.

My solution can be seen [here](https://github.com/alces-software/inventoryware/commit/17fe28a33659b1e6c024c50fea911c938509b01f).
